[auth.cookie]
key = "CrzVMA!r*!J3v8UX$^PKg$V2Ro&a&g"
name = "farmenager_auth"
expiry_days = 7

[auth.registration]
access_key = "nie_oplaca_sie"

[auth.credentials.usernames.admin]
name = "Administrator"
password = "$2b$12$KGEFh/YYzKlRZxeUXkl/rOyXrptU279SVTboKl91PIc/cWbjumd5."
email = "admin@example.com"

[turso]
url = "libsql://farmenager-marekorzylowski.aws-us-west-2.turso.io"
auth_token = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODUwMjcyNTMsImlkIjoiMDE5ZjliZTktNTIwMS03OTU0LWJiYmEtNWQyYTMxZDFkMjBmIiwia2lkIjoicU45NGh5T09USUhTZ1FyZl9BOEN5RVEtV2p4MGo2WDRUTDVIOE52dVd2VSIsInJpZCI6ImVjMjVhNzhjLTUxODktNDBhOC05ZDk1LTA3ZWFjNzM1YTAzMSJ9.d9xq-7dTBTsrdOrLec5o2z_cfg72P0iR22aMfVAuTGe9iyvw9V9hJIn1PPaw8dZ7guc6Isl1pFtH9NKtrduLAg"
