[auth.cookie]
key = "CrzVMA!r*!J3v8UX$^PKg$V2Ro&a&g"
name = "farmenager_auth"
expiry_days = 7

[auth.registration]
access_key = "nie_oplaca_sie"

[auth.credentials.usernames.admin]
name = "Administrator"
password = "$2b$12$KGEFh/YYzKlRZxeUXkl/rOyXrptU279SVTboKl91PIc/cWbjumd5."
email = "admin@example.com"

[turso]
url = "libsql://twoja-baza-xxxx.turso.io"
auth_token = "wklej-tutaj-token-wygenerowany-przez-turso-cli"
